apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/smalltown/argocd-galaxy
      revision: main
      directories:
      - path: infrastructure/solar-system/sun/argo*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/smalltown/argocd-galaxy
        targetRevision: main
        path: 'infrastructure/solar-system/sun/{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd