apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: mercury
        url: https://#{IP_ADDRESS}:61001
      - cluster: venus
        url: https://#{IP_ADDRESS}:61002
      - cluster: earth
        url: https://#{IP_ADDRESS}:61003
  template:
    metadata:
      name: '{{cluster}}-prometheus'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/smalltown/argocd-galaxy
        targetRevision: main
        path: infrastructure/solar-system/basic/prometheus
      destination:
        server: '{{url}}'
        namespace: kube-system