apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-quota
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/smalltown/argocd-galaxy
      revision: main
      files:
      - path: "infrastructure/solar-system/earth/continents/**/**/config.json"
  template:
    metadata:
      name: '{{destination.namespace}}-resource-quota'
      labels:
        function: resource-quota
    spec:
      project: '{{project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: '{{source.repoURL}}'
        targetRevision: '{{source.targetRevision}}'
        path: '{{source.path}}'
      destination:
        server: https://#{IP_ADDRESS}:61003
        namespace: '{{destination.namespace}}'